# Generated by Django 2.2.6 on 2019-10-24 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_level_addtimt', models.DateTimeField(default=datetime.datetime.now, verbose_name='告警级别添加时间')),
                ('alarm_level_name', models.CharField(max_length=255, verbose_name='告警级别名称')),
                ('alarm_level_detail', models.CharField(max_length=255, verbose_name='告警级别说明')),
            ],
            options={
                'verbose_name': '告警级别表',
            },
        ),
        migrations.CreateModel(
            name='Alarm_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type_addtimt', models.DateTimeField(default=datetime.datetime.now, verbose_name='告警类型添加时间')),
                ('alarm_type_name', models.CharField(max_length=255, verbose_name='告警类型名称')),
                ('alarm_type_detail', models.CharField(max_length=255, verbose_name='告警类型说明')),
            ],
            options={
                'verbose_name': '告警类型表',
            },
        ),
        migrations.CreateModel(
            name='alarm_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('am_device', models.CharField(max_length=255, verbose_name='告警设备')),
                ('am_contene', models.CharField(max_length=255, verbose_name='告警内容')),
                ('am_status', models.IntegerField(choices=[(1, '待处理'), (2, '待审核'), (3, '审核通过'), (4, '审核未通过')], verbose_name='告警状态')),
                ('am_deal_user', models.IntegerField(verbose_name='告警处理人')),
                ('am_deal_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='告警处理时间')),
                ('am_deal_detail', models.CharField(max_length=255, verbose_name='告警处理说明')),
                ('am_audit_user', models.IntegerField(verbose_name='告警审核人')),
                ('am_audit_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='告警审核时间')),
                ('am_audit_detail', models.CharField(max_length=255, verbose_name='告警审核说明')),
                ('am_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.Alarm_level')),
                ('am_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.Alarm_type')),
                ('scene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenes.Scene')),
            ],
            options={
                'verbose_name': '告警表',
            },
        ),
    ]
