# Generated by Django 2.2.6 on 2019-11-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm_management',
            options={'permissions': (('alarm_detail', '告警处理'), ('alarm_audit', '告警审核')), 'verbose_name': '告警表'},
        ),
    ]
