# Generated by Django 2.2.6 on 2019-10-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_addtime', models.DateTimeField(verbose_name='视频添加时间')),
                ('video_name', models.CharField(max_length=255, verbose_name='视频名称')),
                ('video_detail', models.CharField(max_length=255, verbose_name='视频描述')),
                ('video_address', models.CharField(max_length=255, verbose_name='视频地址')),
                ('video_user', models.CharField(max_length=255, verbose_name='用户名')),
                ('video_passwd', models.CharField(max_length=255, verbose_name='密码')),
            ],
            options={
                'verbose_name': '视频表',
            },
        ),
    ]
