# Generated by Django 2.2.6 on 2019-11-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'permissions': (('video_view', '视频浏览'), ('video_contro', '视频管理')), 'verbose_name': '视频表'},
        ),
    ]
