# Generated by Django 2.2.6 on 2019-10-24 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door_approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='门禁申请时间')),
                ('door_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='申请开始时间')),
                ('door_end', models.DateTimeField(null=True, verbose_name='申请结束时间')),
                ('door_follow', models.CharField(max_length=255, null=True, verbose_name='随行人员')),
                ('door_follownum', models.IntegerField(default=0, verbose_name='随行人数')),
                ('door_detail', models.CharField(max_length=255, null=True, verbose_name='申请说明')),
                ('door_status', models.IntegerField(choices=[(1, '待审核'), (2, '已通过'), (3, '已拒绝')], default=1, verbose_name='申请状态')),
                ('door_user', models.IntegerField(null=True, verbose_name='审核人')),
                ('door_audittime', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='审批时间')),
                ('door_feedback', models.CharField(max_length=255, null=True, verbose_name='审批反馈')),
                ('scene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenes.Scene')),
            ],
            options={
                'verbose_name': '门禁审批表',
            },
        ),
    ]
