# Generated by Django 2.2.6 on 2019-11-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('door_limits', '0003_auto_20191024_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='door_approval',
            options={'permissions': (('door_view', '门禁浏览'), ('door_audit', '门禁审批')), 'verbose_name': '门禁审批表'},
        ),
    ]
