# Generated by Django 2.2.6 on 2019-11-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': (('user_view', '用户浏览'), ('user_contro', '用户管理')), 'verbose_name': '用户表'},
        ),
    ]
