# Generated by Django 2.2.6 on 2019-10-24 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='日志添加时间')),
                ('log_content', models.CharField(max_length=255, verbose_name='日志内容')),
                ('log_module', models.CharField(max_length=255, verbose_name='所属模块')),
                ('scene_id', models.IntegerField(verbose_name='所属场景')),
            ],
            options={
                'verbose_name': '日志表',
            },
        ),
    ]
