# Generated by Django 2.2.6 on 2019-11-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logs_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'permissions': (('log_view', '日志浏览'),), 'verbose_name': '日志表'},
        ),
    ]
