# Generated by Django 2.2.6 on 2019-10-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_auto_20191029_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmlamp',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarmlamp', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='alertor',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertor', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='beam',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beam', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='co2',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co2', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='display',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='flame',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flame', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humidity', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='invade',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invade', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='light',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='methane',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methane', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm25', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoke', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='scenes.Scene', verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='unlocking',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocking', to='scenes.Scene', verbose_name='场景'),
        ),
    ]
