# Generated by Django 2.2.6 on 2019-10-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0003_auto_20191030_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'permissions': (('场景浏览', 'scene_view'), ('场景管理', 'scene_contro')), 'verbose_name': '场景表'},
        ),
    ]
