# Generated by Django 2.2.6 on 2019-10-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0005_auto_20191031_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'get_latest_by': 'publication_date', 'permissions': (('scene_view', '场景浏览'), ('scene_contro', '场景管理')), 'verbose_name': '场景表'},
        ),
    ]
