# Generated by Django 2.2.6 on 2019-10-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0006_auto_20191031_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmlamp',
            options={'ordering': ['-alarmlamp_insert_time'], 'verbose_name': '报警灯表'},
        ),
        migrations.AlterModelOptions(
            name='alertor',
            options={'ordering': ['-alertor_insert_time'], 'verbose_name': '报警器表'},
        ),
        migrations.AlterModelOptions(
            name='beam',
            options={'ordering': ['-beam_insert_time'], 'verbose_name': '光照强度表'},
        ),
        migrations.AlterModelOptions(
            name='co2',
            options={'ordering': ['-co2_insert_time'], 'verbose_name': 'co2的表'},
        ),
        migrations.AlterModelOptions(
            name='display',
            options={'ordering': ['-display_insert_time'], 'verbose_name': '显示器表'},
        ),
        migrations.AlterModelOptions(
            name='fan',
            options={'ordering': ['-fan_insert_time'], 'verbose_name': '风扇表'},
        ),
        migrations.AlterModelOptions(
            name='flame',
            options={'ordering': ['-flame_insert_time'], 'verbose_name': '火光表'},
        ),
        migrations.AlterModelOptions(
            name='humidity',
            options={'ordering': ['-humidity_insert_time'], 'verbose_name': '湿度表'},
        ),
        migrations.AlterModelOptions(
            name='invade',
            options={'ordering': ['-invade_insert_time'], 'verbose_name': '入侵检测表'},
        ),
        migrations.AlterModelOptions(
            name='light',
            options={'ordering': ['-light_insert_time'], 'verbose_name': '灯光表'},
        ),
        migrations.AlterModelOptions(
            name='methane',
            options={'ordering': ['-methane_insert_time'], 'verbose_name': '甲烷表'},
        ),
        migrations.AlterModelOptions(
            name='pm25',
            options={'ordering': ['-pm25_insert_time'], 'verbose_name': 'pm25表'},
        ),
        migrations.AlterModelOptions(
            name='pump',
            options={'ordering': ['-pump_insert_time'], 'verbose_name': '水泵表'},
        ),
        migrations.AlterModelOptions(
            name='scene',
            options={'get_latest_by': 'humidity', 'permissions': (('scene_view', '场景浏览'), ('scene_contro', '场景管理')), 'verbose_name': '场景表'},
        ),
        migrations.AlterModelOptions(
            name='smoke',
            options={'ordering': ['-smoke_insert_time'], 'verbose_name': '烟雾表'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-temperature_insert_time'], 'verbose_name': '温度表'},
        ),
        migrations.AlterModelOptions(
            name='unlocking',
            options={'ordering': ['-unlocking_insert_time'], 'verbose_name': '开锁记录表'},
        ),
    ]
