# Generated by Django 2.2.6 on 2019-11-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0007_auto_20191031_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'permissions': (('scene_view', '场景浏览'), ('scene_contro', '场景管理')), 'verbose_name': '场景表'},
        ),
        migrations.AlterField(
            model_name='display',
            name='display_online',
            field=models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=1, verbose_name='在线状态'),
        ),
    ]
